/*
Copyright (C) Pacific Community (SPC)
Refer to COPYRIGHT and LICENSE files in the root of the repository
*/
///////////////////////////////////////////
// This file is automatically generated. //
// Please do NOT edit !                  //
///////////////////////////////////////////
#ifndef _VERSION_H
#define _VERSION_H

#define VERSION "2.2.7.6"
#define MAJOR_VERSION 2
#define MINOR_VERSION 2
#define REVISION_VERSION 7
#define BUILD_VERSION 6

#endif _VERSION_H
